[options]
addons_path = /mnt/extra-addons/account-financial-tools,/mnt/extra-addons/account-invoicing,/mnt/extra-addons/account-invoice-reporting,/mnt/extra-addons/account-payment,/mnt/extra-addons/argentina-sale,/mnt/extra-addons/miscellaneous,/mnt/extra-addons/multi-company,/mnt/extra-addons/odoo-argentina,/mnt/extra-addons/odoo-argentina-ce,/mnt/extra-addons/product,/mnt/extra-addons/purchase,/mnt/extra-addons/sale,/mnt/extra-addons/sale-workflow,/mnt/extra-addons/server-tools,/mnt/extra-addons/stock,/mnt/extra-addons/stock-logistics-workflow,/mnt/extra-addons/web,/mnt/extra-addons/partner,/mnt/extra-addons/pos,/mnt/custom-addons/confaa-addons
data_dir = /var/lib/odoo
admin_passwd = odoo
dev_mode = True
